name: 'Twistlock Scan'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  scan:
    name: Twistlock Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Twistlock ECR demo
        uses: department-of-veterans-affairs/dots-tools-twistlock-action/twistlock-scan@master
        with:
          REGISTRY_IMAGE_URI: ${{ secrets.REGISTRY_IMAGE_URI }}
          AUDIT_TAG: ${{ secrets.AUDIT_TAG }}
          DOCKER_CONTEXT: '.'
          PCC_CONSOLE_URL: ${{ secrets.PCC_CONSOLE_URL }}
          PCC_USER: ${{ secrets.PCC_USER }}
          PCC_PASS: ${{ secrets.PCC_PASS }}
          RUNNER_ARCHITECTURE: 'x86'
          PRIVATE_REGISTRY: 'ecr'
          ECR_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          ECR_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_REGION_NAME: 'us-gov-west-1'